# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tb_controller.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import request_reply_pb2 as request__reply__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tb_controller.proto\x12\x14tiebreakercontroller\x1a\x13request_reply.proto\"\x95\x01\n\x11\x44\x65ploymentRequest\x12\x13\n\x0bmodel_types\x18\x01 \x03(\t\x12\x0e\n\x06models\x18\x02 \x03(\t\x12\x13\n\x0b\x62\x61tch_sizes\x18\x03 \x03(\x05\x12\x0c\n\x04slos\x18\x04 \x03(\x03\x12\x13\n\x0b\x64istro_type\x18\x05 \x01(\t\x12\x0b\n\x03rps\x18\x06 \x01(\x03\x12\x16\n\x0eslo_percentile\x18\x07 \x01(\x05\"H\n\x12\x44\x65ploymentResponse\x12\x32\n\x06status\x18\x01 \x01(\x0b\x32\".tiebreakercontroller.RequestReply\"B\n\x10MigrationRequest\x12\x15\n\runique_mix_id\x18\x01 \x01(\x05\x12\x17\n\x0f\x62reached_status\x18\x02 \x01(\t\"G\n\x11MigrationResponse\x12\x32\n\x06status\x18\x01 \x01(\x0b\x32\".tiebreakercontroller.RequestReply2\xe0\x01\n\x15TieBreaker_Controller\x12\x63\n\x0c\x44\x65ployJobMix\x12\'.tiebreakercontroller.DeploymentRequest\x1a(.tiebreakercontroller.DeploymentResponse\"\x00\x12\x62\n\rMigrateJobMix\x12&.tiebreakercontroller.MigrationRequest\x1a\'.tiebreakercontroller.MigrationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tb_controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPLOYMENTREQUEST']._serialized_start=67
  _globals['_DEPLOYMENTREQUEST']._serialized_end=216
  _globals['_DEPLOYMENTRESPONSE']._serialized_start=218
  _globals['_DEPLOYMENTRESPONSE']._serialized_end=290
  _globals['_MIGRATIONREQUEST']._serialized_start=292
  _globals['_MIGRATIONREQUEST']._serialized_end=358
  _globals['_MIGRATIONRESPONSE']._serialized_start=360
  _globals['_MIGRATIONRESPONSE']._serialized_end=431
  _globals['_TIEBREAKER_CONTROLLER']._serialized_start=434
  _globals['_TIEBREAKER_CONTROLLER']._serialized_end=658
# @@protoc_insertion_point(module_scope)
